// Browser-compatible hash function using Web Crypto API
const generateHash = async (str) => {
    const encoder = new TextEncoder();
    const data = encoder.encode(str);
    const hashBuffer = await crypto.subtle.digest('SHA-256', data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map(b => b.toString(16).padStart(2, '0')).join('').slice(0, 8);
};

// Generate anonymous ID from IP and thread ID
export const generateAnonymousId = async (ip, threadId) => {
    const combined = `${ip}-${threadId}`;
    return await generateHash(combined);
};

/**
 * Formats a post number to have 10 digits with leading zeros
 * @param {number|string} number - The post number to format
 * @returns {string} The formatted post number
 */
export const formatPostNumber = (number) => {
    return number.toString().padStart(10, '0');
};

// Format user ID display
export const formatUserId = (userId, isAnonymous) => {
    if (!userId) return 'Anonymous';
    if (isAnonymous) return `ID:${userId}`;
    return `ID:${userId}`;
};

// Get country flag emoji from country code
export const getCountryFlag = (countryCode) => {
    if (!countryCode) return '';
    const codePoints = countryCode
        .toUpperCase()
        .split('')
        .map(char => 127397 + char.charCodeAt());
    return String.fromCodePoint(...codePoints);
};

// Parse quote references from text
export const parseQuoteRefs = (text) => {
    if (!text) return [];
    const matches = text.match(/>>(\d+)/g) || [];
    return matches.map(ref => {
        const number = ref.substring(2);
        return {
            fullMatch: ref,
            number: parseInt(number, 10)
        };
    });
};

// Validate post number
export const validatePostNumber = (number) => {
    return typeof number === 'number' && number > 0;
};

// Generate a unique post number (this should be handled by the backend)
export const generatePostNumber = () => {
    // This is just a placeholder - actual post numbers should be generated by the backend
    return Math.floor(Math.random() * 100000);
};

// Format timestamp in 4chan style
export const formatTimestamp = (date) => {
    const d = new Date(date);
    const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
    const month = (d.getMonth() + 1).toString().padStart(2, '0');
    const day = d.getDate().toString().padStart(2, '0');
    const year = d.getFullYear().toString().slice(-2);
    const hours = d.getHours().toString().padStart(2, '0');
    const minutes = d.getMinutes().toString().padStart(2, '0');
    const seconds = d.getSeconds().toString().padStart(2, '0');
    const dayName = days[d.getDay()];
    
    return `${month}/${day}/${year}(${dayName})${hours}:${minutes}:${seconds}`;
};

// Format a post number as a quote reference
export const formatQuoteRef = (postNumber) => {
    if (!postNumber) return '';
    return `>>${formatPostNumber(postNumber)}`;
};

// Parse a quote reference
export const parseQuoteRef = (text) => {
    const match = text.match(/>>(\d+)/);
    return match ? parseInt(match[1], 10) : null;
};

// Check if text contains quote references
export const hasQuoteRefs = (text) => {
    return />>\d+/.test(text);
};

// Extract all quote references from text
export const extractQuoteRefs = (text) => {
    if (!text) return [];
    const matches = text.match(/>>\d+/g) || [];
    return matches.map(ref => parseInt(ref.substring(2), 10));
};

/**
 * Detects repeating digits at the end of a post number
 * @param {number|string} postNumber - The post number to check
 * @returns {Object|null} Object containing pattern info or null if no pattern
 */
export const getRepeatingDigits = (postNumber) => {
    const numStr = String(postNumber).padStart(10, '0');
    const match = numStr.match(/(.)\1+$/); // matches ending repeating digits
    
    if (match) {
        const length = match[0].length;
        return {
            count: length,
            digit: match[1],
            label: getPatternLabel(length),
            pattern: match[0]
        };
    }
    return null;
};

/**
 * Gets the label for a repeating digit pattern
 * @param {number} count - Number of repeating digits
 * @returns {string} Pattern label
 */
export const getPatternLabel = (count) => {
    const labels = {
        2: "DUBS",
        3: "TRIPS",
        4: "QUADS",
        5: "QUINTS",
        6: "SEXTS",
        7: "SEPTS",
        8: "OCTS",
        9: "NONAS",
        10: "DECAS"
    };
    return labels[count] || `${count}x`;
};

/**
 * Gets the color class for a pattern based on rarity
 * @param {number} count - Number of repeating digits
 * @returns {string} Tailwind color class
 */
export const getPatternColor = (count) => {
    const colors = {
        2: "text-green-400", // Common
        3: "text-blue-400",  // Uncommon
        4: "text-purple-400", // Rare
        5: "text-pink-400",   // Very rare
        6: "text-red-400",    // Extremely rare
        7: "text-yellow-400", // Legendary
        8: "text-orange-400", // Mythical
        9: "text-indigo-400", // Divine
        10: "text-cyan-400"   // Godlike
    };
    return colors[count] || "text-gray-400";
}; 